from fpdf import FPDF
from datetime import datetime
import uuid
import os

def generate_lungct_report(detections, summary, purpose, observations, info_note, user="User", output_path="Alrafiah_AI_Report_LungCT.pdf"):
    """
    Generate PDF report for Lung CT analysis using Unicode-safe font
    """

    # --- Ensure reports folder exists ---
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # --- Use Unicode TTF font ---
    pdf = FPDF()
    pdf.add_page()
    pdf.add_font('DejaVu', '', 'DejaVuSans.ttf', uni=True)
    pdf.add_font('DejaVu', 'B', 'DejaVuSans-Bold.ttf', uni=True)
    pdf.add_font('DejaVu', 'I', 'DejaVuSans-Oblique.ttf', uni=True)
    pdf.set_font("DejaVu", "", 12)

    # --- Header ---
    try:
        logo_path = "assets/alrafiah_logo.png"
        pdf.image(logo_path, x=10, y=8, w=30)
    except:
        pass
    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(80)
    pdf.cell(30, 10, "Al-Rafiah Medical AI Report", ln=True, align='C')
    pdf.ln(15)

    # --- Case Identification ---
    case_id = f"LC_{datetime.now().strftime('%Y%m%d')}_{uuid.uuid4().hex[:8].upper()}"
    analysis_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.set_font("DejaVu", "B", 14)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(0, 10, "1. CASE IDENTIFICATION", ln=True)
    pdf.ln(5)
    pdf.set_font("DejaVu", "", 11)
    pdf.set_text_color(0,0,0)
    pdf.cell(0,8,f"Case ID: {case_id}", ln=True)
    pdf.cell(0,8,f"Analysis Date & Time: {analysis_datetime}", ln=True)
    pdf.cell(0,8,f"Generated for: {user}", ln=True)
    pdf.cell(0,8,"Organ System: Lung", ln=True)
    pdf.ln(10)

    # --- Summary ---
    pdf.set_font("DejaVu", "B", 14)
    pdf.set_text_color(19,71,52)
    pdf.cell(0,10,"2. SUMMARY", ln=True)
    pdf.ln(5)
    pdf.set_font("DejaVu", "", 11)
    pdf.set_text_color(0,0,0)
    pdf.multi_cell(0,8,summary)
    pdf.ln(10)

    # --- Purpose ---
    if purpose:
        pdf.set_font("DejaVu", "B", 14)
        pdf.set_text_color(19,71,52)
        pdf.cell(0,10,"3. PURPOSE", ln=True)
        pdf.ln(5)
        pdf.set_font("DejaVu", "", 11)
        pdf.multi_cell(0,8,purpose)
        pdf.ln(10)

    # --- Observations ---
    if observations:
        pdf.set_font("DejaVu", "B", 14)
        pdf.set_text_color(19,71,52)
        pdf.cell(0,10,"4. OBSERVATIONS", ln=True)
        pdf.ln(5)
        pdf.set_font("DejaVu", "", 11)
        pdf.multi_cell(0,8,observations)
        pdf.ln(10)

    # --- Detected Nodules ---
    if detections and len(detections)>0:
        pdf.set_font("DejaVu", "B", 14)
        pdf.set_text_color(19,71,52)
        pdf.cell(0,10,"5. DETECTED NODULES", ln=True)
        pdf.ln(5)
        pdf.set_font("DejaVu", "", 11)
        for det in detections:
            conf = det.get("confidence",0)
            if isinstance(conf,str):
                conf = float(conf.replace('%',''))
            pdf.cell(0,8,f"Nodule ID: {det.get('nodule_id','-')}", ln=True)
            pdf.cell(0,8,f"Confidence: {conf:.1f}%", ln=True)
            pdf.cell(0,8,f"Location: {det.get('location','-')}", ln=True)
            pdf.cell(0,8,f"Size: {det.get('size','-')}", ln=True)
            pdf.cell(0,8,f"Priority: {det.get('priority','-')}", ln=True)
            pdf.ln(5)

    # --- Additional Info ---
    if info_note:
        pdf.set_font("DejaVu", "B", 14)
        pdf.set_text_color(19,71,52)
        pdf.cell(0,10,"6. ADDITIONAL INFORMATION", ln=True)
        pdf.ln(5)
        pdf.set_font("DejaVu", "", 11)
        pdf.multi_cell(0,8,info_note)
        pdf.ln(10)

    # --- Disclaimer ---
    pdf.set_font("DejaVu", "B", 12)
    pdf.set_text_color(150,0,0)
    pdf.cell(0,10,"IMPORTANT DISCLAIMER", ln=True)
    pdf.ln(2)
    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(100,100,100)
    disclaimer_text = (
        "This AI-generated report is intended for research and educational purposes only. "
        "It should not be used as a substitute for professional medical diagnosis or treatment decisions. "
        "All results require validation by qualified medical professionals. "
        "Clinical correlation and expert review are essential for final diagnosis."
    )
    pdf.multi_cell(0,6,disclaimer_text)
    pdf.ln(10)

    # --- Footer ---
    pdf.set_font("DejaVu", "I", 9)
    pdf.set_text_color(100,100,100)
    pdf.cell(0,10,f"Generated by Al-Rafiah Lung CT AI | {analysis_datetime}", ln=True, align='C')

    pdf.output(output_path)
    return output_path
