from fpdf import FPDF
from datetime import datetime
import uuid

def generate_breast_report(analysis_type, result, confidence, image_name, output_path="Alrafiah_AI_Report_Breast.pdf"):
    """
    Generate PDF report for breast cancer model ONLY
    
    Args:
        analysis_type: Type of analysis (e.g., "Histology")
        result: Breast model result (e.g., "Malignant (Ductal Carcinoma)")
        confidence: Confidence percentage (e.g., 97.3)
        image_name: Name of analyzed image
        output_path: Path to save PDF
    """
    
    # Parse breast model result: "Malignant (Ductal Carcinoma)"
    if "(" in result and ")" in result:
        classification = result.split("(")[0].strip()
        subtype = result.split("(")[1].replace(")", "").strip()
    else:
        classification = result
        subtype = "Not specified"
    
    # Generate case ID for breast
    case_id = f"BC_{datetime.now().strftime('%Y%m%d')}_{uuid.uuid4().hex[:8].upper()}"
    analysis_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Create PDF
    pdf = FPDF()
    pdf.add_page()

    # --- Header with Logo ---
    try:
        logo_path = "assets/alrafiah_logo.png"
        pdf.image(logo_path, x=10, y=8, w=30)
    except:
        pass  # Continue without logo if not found

    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(80)
    pdf.cell(30, 10, "Al-Rafiah Medical AI Report", ln=True, align='C')
    pdf.ln(15)

    # --- 1. Case Identification Section ---
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(0, 10, "1. CASE IDENTIFICATION", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Case ID: {case_id}", ln=True)
    pdf.cell(0, 8, f"Analysis Date & Time: {analysis_datetime}", ln=True)
    pdf.cell(0, 8, f"Image File: {image_name}", ln=True)
    pdf.cell(0, 8, f"Organ System: Breast", ln=True)
    pdf.ln(10)

    # --- 2. Image Analysis Summary Section ---
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(0, 10, "2. IMAGE ANALYSIS SUMMARY", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    
    # Classification Result
    cancer_status = "Cancerous" if classification.lower() == "malignant" else "Non-cancerous"
    
    pdf.cell(0, 8, f"Classification Result: {cancer_status}", ln=True)
    pdf.cell(0, 8, f"Model Confidence Score: {confidence:.1f}%", ln=True)
    pdf.cell(0, 8, f"Analysis Type: {analysis_type}", ln=True)
    pdf.ln(10)

    # --- 3. Diagnostic Interpretation Section ---
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(0, 10, "3. DIAGNOSTIC INTERPRETATION", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Primary Classification: {classification}", ln=True)
    pdf.cell(0, 8, f"Specific Subtype: {subtype}", ln=True)
    pdf.ln(5)

    # Add confidence interpretation
    confidence_level, interpretation = get_breast_confidence_interpretation(confidence)
    pdf.cell(0, 8, f"Confidence Level: {confidence_level} ({confidence:.1f}%)", ln=True)
    pdf.multi_cell(0, 8, f"Interpretation: {interpretation}")
    pdf.ln(10)

    # --- 4. Clinical Notes Section ---
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(19, 71, 52)
    pdf.cell(0, 10, "4. CLINICAL NOTES", ln=True)
    pdf.ln(5)

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    
    # Breast-specific clinical recommendations
    recommendation = get_breast_clinical_recommendation(confidence, classification)
    pdf.multi_cell(0, 8, f"Recommendation: {recommendation}")
    pdf.ln(5)

    # --- Important Disclaimer ---
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(150, 0, 0)
    pdf.cell(0, 10, "IMPORTANT DISCLAIMER", ln=True)
    pdf.ln(2)

    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(100, 100, 100)
    disclaimer_text = ("This AI-generated report is intended for research and educational purposes only. "
                      "It should not be used as a substitute for professional medical diagnosis or treatment decisions. "
                      "All results require validation by qualified medical professionals. "
                      "Clinical correlation and expert pathologist review are essential for final diagnosis.")
    
    pdf.multi_cell(0, 6, disclaimer_text)
    pdf.ln(10)

    # --- Footer ---
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Generated by Al-Rafiah Breast Cancer AI | {analysis_datetime}", ln=True, align='C')

    # Save PDF
    pdf.output(output_path)
    return output_path

def get_breast_confidence_interpretation(confidence):
    """Get confidence interpretation specific to breast cancer analysis"""
    if confidence >= 95:
        return "Very High", "Strong indication based on histopathological features"
    elif confidence >= 85:
        return "High", "Good confidence in breast tissue classification"
    elif confidence >= 70:
        return "Moderate", "Moderately confident result, clinical correlation advised"
    else:
        return "Low", "Low confidence result, expert breast pathologist review recommended"

def get_breast_clinical_recommendation(confidence, classification):
    """Get clinical recommendations specific to breast cancer"""
    is_malignant = classification.lower() == "malignant"
    
    if confidence >= 90:
        if is_malignant:
            return "High confidence malignant result. Recommend immediate oncology consultation, staging workup, and multidisciplinary team evaluation for treatment planning."
        else:
            return "High confidence benign result. Routine breast cancer surveillance appropriate per clinical guidelines."
    elif confidence >= 70:
        return "Moderate confidence result for breast tissue. Clinical correlation with imaging findings and expert breast pathologist review recommended."
    else:
        return "Low confidence result. Manual histopathological review by specialized breast pathologist required before clinical decision."